Greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('store/',include('store.urls')),
    path('cart/',include('cart.urls')),
    path('account/',include('accounts.urls')),




]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('add_cart_quantity/<int:product_id>/<int:cart_item_id>/',views.add_cart_quantity,name='add_cart_quantity'),

    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/',views.delete_cart_item,name='delete_cart_item'),

    path('checkout/',views.checkout,name='checkout'),





]

store/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.Store,name='store'),
    path('<slug:category_slug>/',views.Store,name='get_product_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/',views.product_detail,name='product_detail'),
    path('search/keyword',views.search,name='search'),



   
]

cart/models.py
from django.db import models
from store.models import Product,variations
from accounts.models import Account
# Create your models here.

class Cart(models.Model):
    cart_id       = models.CharField(max_length=500,)
    date_added    = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    
class Cart_items(models.Model):
    user       = models.ForeignKey(Account, on_delete=models.CASCADE,null=True)
    product    = models.ForeignKey(Product , on_delete=models.CASCADE)
    variation  = models.ManyToManyField(variations , blank=True,null=True)
    cart       = models.ForeignKey(Cart , on_delete=models.CASCADE,null=True)
    quantity   = models.IntegerField()
    is_active  = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product.product_name

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    category        = models.ForeignKey(Category , on_delete=models.CASCADE)
    product_name    = models.CharField(max_length=250,unique=True)
    slug            = models.SlugField(max_length=550,unique=True)
    discription     = models.TextField()
    price           = models.IntegerField()
    stock           = models.IntegerField()
    product_image   = models.ImageField(upload_to='media/product/', blank=True)
    created         = models.DateTimeField(auto_now_add=True)
    modefied        = models.DateTimeField(auto_now=True)
    is_avalible     = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name
    
    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug,])
    

variation_catagiry_choices=(
    ('color','color'),
    ('size','size'),
)

class variationmanager(models.Manager):
    def color(self):
        return super(variationmanager,self).filter(variation_category='color',is_active=True)
    def size(self):
        return super(variationmanager,self).filter(variation_category='size',is_active=True)
    
class variations(models.Model):
    product               = models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category    = models.CharField(max_length=50, choices=variation_catagiry_choices)
    variation_value       = models.CharField(max_length=50)
    is_active             = models.BooleanField(default=True)
    created               = models.DateField(auto_now_add=True)

    objects=variationmanager()

    def __str__(self):
        return self.variation_value

cart/views.py
from django.shortcuts import render,redirect
from store.models import Product,variations
from .models import Cart , Cart_items
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart= request.session.create()
    return cart





def add_cart(request,product_id):

    if request.user.is_authenticated:
        print('enter in is_authenticated')
        current_user=request.user
        print(current_user)
        product= Product.objects.get(id=product_id)
        product_variations=[]
        if request.method=='POST':
            for item in request.POST:
                key=item
                value=request.POST[key]
                print(key,value)
                try:
                    variation= variations.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=value)
                    product_variations.append(variation)
                    print('got variations')
                
                except:
                    pass
            
        is_cart_item_exist=Cart_items.objects.filter(product=product,user=current_user).exists()
        print(is_cart_item_exist)
        if is_cart_item_exist:
            try:
                cart_items= Cart_items.objects.get(product=product,user=current_user,variation=variation)
                cart_items.quantity += 1
                cart_items.save()
            except Cart_items.DoesNotExist:
                cart_items= Cart_items.objects.create(product=product,user=current_user,quantity=1)
                cart_items.variation.clear()
                for items in product_variations:
                    cart_items.variation.add(items)
                cart_items.save()
        else:
            print('enter in else block')
            cart_items= Cart_items.objects.create(user=current_user,product=product,quantity=1)
            print('enter in else block line 2')
            cart_items.variation.clear()
            for items in product_variations:
                print('enter in else block line ',items)
                
                cart_items.variation.add(items)
            print('enter in else block after the for loop ')
            

            cart_items.save()

        return redirect( 'cart')

    #if user is not Authenticated 
    else:
        product= Product.objects.get(id=product_id)
        product_variations=[]
        if request.method=='POST':
            for item in request.POST:
                key=item
                value=request.POST[key]
                print(key,value)
                try:
                    variation= variations.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=value)
                    product_variations.append(variation)
                
                except:
                    pass
            
        try:
        
            cart=Cart.objects.filter(cart_id=_cart_id(request)).exists()
        
            if cart:
                cart=Cart.objects.get(cart_id=_cart_id(request))
            else:
                cart=Cart.objects.create(cart_id=_cart_id(request))
            
                print(cart)
                cart.save()


        except Exception as e:
            print(e)
        

        is_cart_item_exist=Cart_items.objects.filter(product=product,cart=cart).exists()
        if is_cart_item_exist:
            try:
                cart_items= Cart_items.objects.get(product=product,cart=cart,variation=variation)
                cart_items.quantity += 1
                cart_items.save()
            except Cart_items.DoesNotExist:
                cart_items= Cart_items.objects.create(product=product,cart=cart,quantity=1)
                cart_items.variation.clear()
                for items in product_variations:
                    cart_items.variation.add(items)
                cart_items.save()
        else:
            
            cart_items= Cart_items.objects.create(product=product,cart=cart,quantity=1)
            cart_items.variation.clear()
            for items in product_variations:
                cart_items.variation.add(items)

            cart_items.save()

        return redirect( 'cart')


def remove_cart(request,product_id,cart_item_id):
    product= Product.objects.get(id=product_id)
    if request.user.is_authenticated:
        cart_item=Cart_items.objects.get(product=product,user=request.user,id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()

        else:
            cart_item.delete()
    else:

        cart=Cart.objects.get(cart_id=_cart_id(request))
    
        cart_item=Cart_items.objects.get(product=product,cart=cart,id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()

        else:
            cart_item.delete()

    return redirect('cart')


def add_cart_quantity(request,product_id,cart_item_id):
    product= Product.objects.get(id=product_id)
    if request.user.is_authenticated:
         cart_item=Cart_items.objects.get(product=product,user=request.user,id=cart_item_id)
         cart_item.quantity += 1
         cart_item.save()
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item=Cart_items.objects.get(product=product,cart=cart,id=cart_item_id)
        cart_item.quantity += 1
        cart_item.save()

    return redirect('cart')
   


def delete_cart_item(request,product_id,cart_item_id):
    product= Product.objects.get(id=product_id,)
    if request.user.is_authenticated:
        cart_item=Cart_items.objects.get(product=product,user=request.user,id=cart_item_id)
        cart_item.delete()
        
    else:
        
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item=Cart_items.objects.get(product=product,cart=cart,id=cart_item_id)
        cart_item.delete()
    return redirect('cart')





 

def cart(request):

    # cart=Cart.objects.get(cart_id=_cart_id(request))
    if request.user.is_authenticated:
        cart_items=Cart_items.objects.filter(user=request.user)
    else:
        cart_items=Cart_items.objects.filter(cart__cart_id=_cart_id(request))
    total=0
    quantiy=0
    for cart_item in cart_items:
        Total = (cart_item.product.price * cart_item.quantity)
        total += Total
        quantiy += cart_item.quantity

    tax= (2*total)/100
    grand_total=total+tax
    cart_items_count=cart_items.count()
       

    context={
        'cart_items':cart_items,
        'total':total,
        'grand_total':grand_total,
        'tax':tax,
        'quantiy':quantiy,
        'cart_items_count':cart_items_count

    }

    return render(request,'store/cart.html',context)

@login_required(login_url='signin')
def checkout(request):
    if request.user.is_authenticated:
        cart_items=Cart_items.objects.filter(user=request.user)
    else:
        cart_items=Cart_items.objects.filter(cart__cart_id=_cart_id(request))
    total=0
    quantiy=0
    for cart_item in cart_items:
        Total = (cart_item.product.price * cart_item.quantity)
        total += Total
        quantiy += cart_item.quantity

    tax= (2*total)/100
    grand_total=total+tax
    cart_items_count=cart_items.count()
       

    context={
        'cart_items':cart_items,
        'total':total,
        'grand_total':grand_total,
        'tax':tax,
        'quantiy':quantiy,
        'cart_items_count':cart_items_count

    }
    return render(request,'store/checkout.html',context)

store/views.py
from django.shortcuts import render
from .models import Product 
from category.models import Category
from django.http import Http404
from cart.models import Cart_items
from cart.views import _cart_id
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.db.models import Q
from django.contrib.auth.decorators import login_required

# Create your views here.


def Store(request,category_slug=None):
  

    if category_slug != None:
        category=Category.objects.get(slug=category_slug)
        products= Product.objects.filter(category=category)
        paginator=Paginator(products,1)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)

        product_count=products.count()
    else:

        products= Product.objects.all().filter(is_avalible=True).order_by('id')
        paginator=Paginator(products,6)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)
        product_count=products.count()
    context={
        'products' :paged_products,
        'product_count':product_count

    }
    return render(request,'store/store.html',context)


def product_detail(request,category_slug,product_slug):
    product=None
    try:
        product=Product.objects.get(slug=product_slug,category__slug=category_slug,)
        in_cart=Cart_items.objects.filter(cart__cart_id=_cart_id(request),product=product).exists()

    except Product.DoesNotExist:
        raise Http404("Product not found")
    context={
        'product':product,
        'in_cart':in_cart
    }
    return render(request,'store/product_detail.html',context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET.get('keyword')
        if keyword:
            products=Product.objects.filter(Q(product_name__icontains=keyword) | Q(discription__icontains=keyword)).order_by('id')
        else:
            pass
        product_count=products.count()
        context={
            'products':products,
            'product_count':product_count
        }
        return render(request,'store/store.html',context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static%}
{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if cart_items_count >= 1%}
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
    {% for cartitem in cart_items%}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <a href="{{cartitem.product.get_url}}"><div class="aside"><img src="{{cartitem.product.product_image.url}}" class="img-sm"></div></a>
                <figcaption class="info">
                    <a href="#" class="title text-dark">{{cartitem.product.product_name}}</a>
                    <p class="text-muted small">
                        {% for items in cartitem.variation.all%}
                        {{items.variation_category}} : {{items.variation_value}} <br>
                        {% endfor %}
                    </p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'remove_cart' cartitem.product.id cartitem.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{cartitem.quantity}}">
                                <div class="input-group-append">
                                <a href="{% url 'add_cart_quantity' cartitem.product.id cartitem.id%}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">${{cartitem.sub_total}}</var> 
                <small class="text-muted"> ${{cartitem.product.price}} each </small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'delete_cart_item' cartitem.product.id  cartitem.id %}" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
    {% endfor%}
    
   
   
   
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'checkout'%}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    {% else %}
      <h2 class="text-center">No items added to the cart</h2>
      <br>
      <div class="text-center" center>
        <a href="{% url 'home'%}" class="btm btn-primary">continue shoping</a>
      </div>

    {%endif%}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load static%}
{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
   
    <div class="row">
        <aside class="col-lg-6">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title mb-4">Billing Address</h4>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col form -group">
                        <label for="">First Name</label>
                        <input type="text" name="first_name" class="form-control" required>
                    </div>
                    <div class="col form -group">
                        <label for="">Last Name</label>
                        <input type="text" name="last_name" class="form-control" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form -group">
                        <label for="">Email</label>
                        <input type="email" name="email" class="form-control" required>
                    </div>
                    <div class="col form -group">
                        <label for="">Phone Number</label>
                        <input type="text" name="phone_number" class="form-control" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form -group">
                        <label for="">Address line 1</label>
                        <input type="text" name="address_lin1" class="form-control" required>
                    </div>
                    <div class="col form -group">
                        <label for="">Address lin 2</label>
                        <input type="text" name="address_lin2" class="form-control" >
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form -group">
                        <label for="">City</label>
                        <input type="text" name="city" class="form-control" required>
                    </div>
                    <div class="col form -group">
                        <label for="">State</label>
                        <input type="text" name="state" class="form-control" >
                    </div>
                    <div class="col form -group">
                        <label for="">Pincode</label>
                        <input type="text" name="pincode" class="form-control" >
                    </div>
                </div>
                <div class="col form -group">
                    <label for="">Order Note</label>
                    <textarea type="text" name="order_note" rows="2" class="form-control" ></textarea>
                </div>
           
        </div>
   
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-6">
    
            <div class="card">
            <div class="card-body">
                <table class="table table-borderless table-shopping-cart">
                    <thead class="text-muted">
                    <tr class="small text-uppercase">
                      <th scope="col">Product</th>
                      <th scope="col" width="120">Quantity</th>
                      <th scope="col" width="120">Price</th>
                    
                    </tr>
                    </thead>
                    <tbody>
                    {% for cartitem in cart_items%}
                    <tr>
                        <td>
                            <figure class="itemside align-items-center">
                                <a href="{{cartitem.product.get_url}}"><div class="aside"><img src="{{cartitem.product.product_image.url}}" class="img-sm"></div></a>
                                <figcaption class="info">
                                    <a href="#" class="title text-dark">{{cartitem.product.product_name}}</a>
                                    <p class="text-muted small">
                                        {% for items in cartitem.variation.all%}
                                        {{items.variation_category}} : {{items.variation_value}} <br>
                                        {% endfor %}
                                    </p>
                                </figcaption>
                            </figure>
                        </td>
                        <td> 
                           <label for="">{{cartitem.quantity}}</label>
                        </td>
                        <td> 
                            <div class="price-wrap"> 
                                <var class="price">${{cartitem.sub_total}}</var> 
                                <small class="text-muted"> ${{cartitem.product.price}} each </small> 
                            </div> <!-- price-wrap .// -->
                        </td>
                       
                    </tr>
                    {% endfor%}
                    
                   
                   
                   
                    </tbody>
                    </table>
             
              
                <button type="submit" name="submit" class="btn btn-primary btn-block" >Place Order</button>
                <a href="{% url 'store'%}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
        </form>
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
   
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{%load static%}
{% block content %}
    



<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{product.product_image.url}}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
    <form action="{% url 'add_cart' product.id %}" method="POST">
      {% csrf_token %}
                </aside>
                <main class="col-md-6 border-left">
        <article class="content-body">
        
        <h2 class="title">{{product.product_name}}</h2>
        
        <div class="mb-3"> 
            <var class="price h4">${{product.price}}</var> 
        </div> 
        
        <p>Virgil Abloh’s Off-White is a streetwear-inspired collection that continues to break away from the conventions of mainstream fashion. Made in Italy, these black and brown Odsy-1000 low-top sneakers.</p>
        
        
        <hr>
            <div class="row">
                <div class="item-option-select" >
                    <h6>Choose Color</h6>
                    {% for i in product.variations_set.color %}
                    <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons" >
                      <label class="btn btn-light">
                        <input type="radio" name="color" value="{{i.variation_value}}" required > {{i.variation_value |capfirst}} 
                      </label>
                      
                    </div> 
                    {% endfor %}
                </div>
            </div> <!-- row.// -->
            <div class="row">
                <div class="item-option-select" >
                    <h6>Select Size</h6>
                    {% for i in product.variations_set.size %}
                    <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons" >
                      <label class="btn btn-light" >
                        <input type="radio" name="size" value="{{i.variation_value}}" required > {{i.variation_value}}
                      </label>
                    </div> 
                    {% endfor %}
                </div>
            </div> <!-- row.// -->
            <hr>
            {% if product.stock <= 0 %}
            <h2 >Out of stock</h2>
            {%else%}
            <button  type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
            
            <!-- <a href="{% url 'add_cart' product.id %}" class="btn  btn-outline-primary"> <span class="text">View cart</span> <i class="fas fa-eye"></i>  </a> -->
            {% endif %}
      </form>
    </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    {% endblock %}